# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ Ordering algorithm
#' 
#' @param x A numeric vector to be ordered
#' @param decreasing Set to TRUE or FALSE to order in decreasing order
#' @export
order_cpp <- function(x, decreasing = FALSE) {
    .Call(`_rdsmart_order_cpp`, x, decreasing)
}

#' C++ Sorting algorithm
#' 
#' @param x A numeric vector to be sorted
#' @param decreasing set to TRUE or FALSE to sort in decreasing order
#' @param nalast Place NA values at the end of the string?
#' @export
sort_cpp <- function(x, decreasing = FALSE, nalast = FALSE) {
    .Call(`_rdsmart_sort_cpp`, x, decreasing, nalast)
}

